# Kindle Review Sentiment Analysis

# About Dataset

Context This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

Content 5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.


## Columns

asin - ID of the product, like B000FA64PK

helpful - helpfulness rating of the review - example: 2/3.

overall - rating of the product.

reviewText - text of the review (heading).

reviewTime - time of the review (raw).

reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN

reviewerName - name of the reviewer.

summary - summary of the review (description).

unixReviewTime - unix timestamp.

Acknowledgements This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/

License to the data files belong to them.

Inspiration

Sentiment analysis on reviews.
Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
Fake reviews/ outliers.
Best rated product IDs, or similarity between products based on reviews alone (not the best idea ikr).
Any other interesting analysis

# Best Practises

1. preprocessing and cleaning.

2. TRain Test Split.

3. BOW,TF-IDF,Word2Vec.

4. Train ML Algorithm

In [14]:
## Load dataset
import pandas as pd
data=pd.read_csv('C:\\NLP\\nlp-project2\\Kindle Reviews\\all_kindle_review.csv')
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [15]:
# choose important columns
df=data[['reviewText','rating']]

df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [16]:
df.shape

(12000, 2)

In [17]:
# check for missing values:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [18]:
# check for unique values in the rating column
df['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [19]:
# check count of each rating
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

# preprocessing and cleaning

In [20]:
# Positive reviews=1==>3
# Negative reviews=0==>1,2
df['rating'] = df['rating'].apply(lambda x: 0 if x < 3 else 1)

C:\Users\owais\AppData\Local\Temp\ipykernel_18480\240330696.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].apply(lambda x: 0 if x < 3 else 1)


In [21]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [22]:
# lowercase the reviews
df['reviewText'] = df['reviewText'].str.lower()

C:\Users\owais\AppData\Local\Temp\ipykernel_18480\1402176893.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].str.lower()


In [23]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

# data cleaning

In [24]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\owais\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [37]:
!pip install beautifulsoup4
from bs4 import BeautifulSoup

In [38]:
!pip install lxml

In [39]:
# Remove special characters
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x))

# Remove stop words
df['reviewText'] = df['reviewText'].apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords.words('english')]))

# Remove urls
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub(r'http\S+|www\S+|https\S+', '', x, flags=re.MULTILINE))

# Remove extra spaces
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\owais\AppData\Local\Temp\ipykernel_18480\876403542.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x))
C:\Users\owais\AppData\Local\Temp\ipykernel_18480\876403542.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords.words('english')]))
C:\Users\owais\AppData\Local\Temp\ipykernel_18480\876403542.py:8: Se

In [43]:
# remove html tags
from bs4 import BeautifulSoup
df['reviewText'] = df['reviewText'].apply(lambda x: BeautifulSoup(x, "html.parser").get_text())

C:\Users\owais\AppData\Local\Temp\ipykernel_18480\3112339877.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x: BeautifulSoup(x, "html.parser").get_text())


In [44]:
df.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

# Lemmatization

In [46]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# Lemmatize the words
def lemmatize_text(text):
    return ' '.join([lemmatizer.lemmatize(word) for word in text.split()])

In [47]:
df['reviewText'] = df['reviewText'].apply(lambda x: lemmatize_text(x)).str.lower()

C:\Users\owais\AppData\Local\Temp\ipykernel_18480\1700233953.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x: lemmatize_text(x)).str.lower()


In [48]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

# Train Test SPlit

In [60]:
# Train-test split
from sklearn.model_selection import train_test_split
X = df['reviewText']
y = df['rating']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [61]:
x_train.shape, y_train.shape, X_test.shape, y_test.shape

((9600,), (9600,), (2400,), (2400,))

In [63]:
# create bag of words model
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()

x_train_bow = bow.fit_transform(x_train).toarray()
x_test_bow = bow.transform(x_test).toarray()

print(x_train_bow.shape, x_test_bow.shape)


(9600, 37355) (2400, 37355)


In [64]:
# create tf-idf model
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

x_train_tfidf = tfidf.fit_transform(x_train).toarray()
x_test_tfidf = tfidf.transform(x_test).toarray()

print(x_train_tfidf.shape, x_test_tfidf.shape)

(9600, 37355) (2400, 37355)


In [67]:
x_train_bow 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [68]:
x_train_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Model Training

In [ ]:
# Train GussianNB model
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train_bow, y_train)
y_pred_bow = gnb.predict(x_test_bow)
y_pred_bow




array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [71]:
gnb.fit(x_train_tfidf, y_train)
y_pred_tfidf = gnb.predict(x_test_tfidf)
print(y_pred_tfidf)


[0 0 0 ... 1 0 1]


# performance Matrics

In [72]:
# Evaluate the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy (Bag of Words):", accuracy_score(y_test, y_pred_bow))
print("Classification Report (Bag of Words):\n", classification_report(y_test, y_pred_bow))
print("Confusion Matrix (Bag of Words):\n", confusion_matrix(y_test, y_pred_bow))

Accuracy (Bag of Words): 0.5779166666666666
Classification Report (Bag of Words):
               precision    recall  f1-score   support

           0       0.41      0.62      0.50       803
           1       0.75      0.56      0.64      1597

    accuracy                           0.58      2400
   macro avg       0.58      0.59      0.57      2400
weighted avg       0.63      0.58      0.59      2400

Confusion Matrix (Bag of Words):
 [[500 303]
 [710 887]]


In [73]:
print("Accuracy (TF-IDF):", accuracy_score(y_test, y_pred_tfidf))
print("Classification Report (TF-IDF):\n", classification_report(y_test, y_pred_tfidf))
print("Confusion Matrix (TF-IDF):\n", confusion_matrix(y_test, y_pred_tfidf))


Accuracy (TF-IDF): 0.5791666666666667
Classification Report (TF-IDF):
               precision    recall  f1-score   support

           0       0.41      0.60      0.49       803
           1       0.74      0.57      0.64      1597

    accuracy                           0.58      2400
   macro avg       0.58      0.58      0.57      2400
weighted avg       0.63      0.58      0.59      2400

Confusion Matrix (TF-IDF):
 [[483 320]
 [690 907]]


NOTE=

1. Using Bow and tf-idf our accuracy is low

2. To increase accuracy we use word2vec and average word2vec

# Word2Vec and Avg Word2vec

In [81]:
import gensim
from gensim.models import Word2Vec
model = Word2Vec(sentences=df['reviewText'].apply(lambda x: x.split()), vector_size=100)
model.save("word2vec.model")

In [82]:
model

In [99]:
# Average the word vectors for each review
def average_word_vectors(text):
    
    return np.mean([model.wv[word] for word in text.split() if word in model.wv], axis=0)

In [100]:
!pip install tqdm

In [101]:
from tqdm import tqdm
import numpy as np
# create a list to store the average word vectors for each sentence
x = []
for i in tqdm(range(len(df))):
    x.append(average_word_vectors(df['reviewText'][i]))

100%|██████████| 12000/12000 [00:04<00:00, 2650.77it/s]


In [102]:
x

[array([-0.1835378 ,  0.35770732,  0.21618867,  0.04110308, -0.06274931,
        -0.46665898,  0.04274263,  0.6554213 , -0.25454855, -0.17400455,
        -0.04493856, -0.2577115 , -0.09986431,  0.04874212,  0.01782139,
        -0.30176678,  0.14738624, -0.4704297 ,  0.15096965, -0.50678647,
         0.0693799 ,  0.11458855,  0.0561107 , -0.0651938 , -0.11938019,
         0.01053039, -0.21822841, -0.02224554, -0.36160615,  0.16323842,
         0.40996742, -0.15549202,  0.11865295, -0.10176799, -0.20699671,
         0.2689781 ,  0.08824782, -0.35915393, -0.04866754, -0.57925814,
        -0.11748329, -0.3024744 , -0.1306077 ,  0.03886058,  0.08474364,
        -0.18496864, -0.10749849, -0.05382282,  0.12945408,  0.16678624,
         0.09520312, -0.21545634, -0.04609254,  0.10455272, -0.24582091,
         0.17448142,  0.17920439, -0.02488321, -0.30905133, -0.03376798,
         0.09148221,  0.18012497, -0.01272717, -0.04348728, -0.36175948,
         0.30483314,  0.19725642,  0.19124216, -0.5

# independent and dependent features

In [103]:
x_new = np.array(x, dtype=object)
x_new

array([[-0.1835377961397171, 0.35770732164382935, 0.21618866920471191,
        ..., -0.2369385063648224, 0.20186319947242737,
        -0.051826853305101395],
       [-0.3569211959838867, 0.32762202620506287, -0.14946366846561432,
        ..., -0.20595864951610565, 0.05663464590907097,
        -0.07956618070602417],
       [-0.3602728843688965, 0.3511233329772949, 0.07302780449390411,
        ..., -0.2228097915649414, 0.012948194518685341,
        -0.034896448254585266],
       ...,
       [-0.39772501587867737, 0.3699120283126831, 0.0032960576936602592,
        ..., -0.06225086376070976, 0.17508307099342346,
        -0.07243812829256058],
       [0.24178330600261688, 0.43336471915245056, 0.27627259492874146,
        ..., -0.35628193616867065, 0.01907799392938614,
        0.11543592065572739],
       [-0.25060269236564636, 0.274880975484848, 0.08943004161119461,
        ..., -0.19189000129699707, 0.06884972006082535,
        -0.13824835419654846]], dtype=object)

In [104]:
# depedent variable
y = df['rating'].values
y

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [105]:
#Train-test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size=0.20, random_state=42)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((9600, 100), (9600,), (2400, 100), (2400,))

In [106]:
#model training
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_pred = gnb.predict(x_test)
y_pred

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [107]:
# evaluate the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy (Word2Vec):", accuracy_score(y_test, y_pred))
print("Classification Report (Word2Vec):\n", classification_report(y_test, y_pred))
print("Confusion Matrix (Word2Vec):\n", confusion_matrix(y_test, y_pred))

Accuracy (Word2Vec): 0.7341666666666666
Classification Report (Word2Vec):
               precision    recall  f1-score   support

           0       0.58      0.76      0.66       803
           1       0.86      0.72      0.78      1597

    accuracy                           0.73      2400
   macro avg       0.72      0.74      0.72      2400
weighted avg       0.76      0.73      0.74      2400

Confusion Matrix (Word2Vec):
 [[ 611  192]
 [ 446 1151]]


NOTE= 

1. Using word2vec the accuracy has been increased.

2. we can also perform hyperparameter tunning to get more accurate results